### ISSUE TITLE
Can someone help me with the patch code step?

### ISSUE THREAD

**Issue by juanml1979** [MagicFoundation/Alcinoe#173] opened 2021-05-04 07:14 UTC
Can someone help me with the patching ?

Hi, I'm very clumsy and I can't patch the code using the bat file: C:\developframeworkcomponentsdelphi-10.4.4alcinoeembarcadero\sydney\10_4_2_2_update.bat

This batch file copies the files fine, but when I run the patch I get errors when I run "git apply command" like: 

Patch the source code
Checking patch patch embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.Helpers.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.Helpers.pas: No such file or directory

What can I do?. I think it's probably very simple but I don't know how I can solve it

Could someone please help me please?

**Comment by Zeus64** [comment] 2021-05-04 08:54
do you have the file <alcinoe_root>/embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.Helpers.pas ?

**Comment by juanml1979** [comment] 2021-05-04 12:53
Thank you very much for your rapid response. 

Yes the first part of update.bat runs well. I have two folders in <alcinoe_root>/embarcadero/sydney/10_4_2/ , fmx and rtl (with  android ios and win folders inside). I have 508 files in 5 folders.

The problem start after "git apply sydney_10_4_2.patch -v" 

Patch the source code
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.Helpers.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.Helpers.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Canvas.GPU.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Context.GLES.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Context.GLES.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Controls.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Controls.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Dialogs.iOS.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Dialogs.iOS.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Edit.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Edit.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Filter.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Filter.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Forms.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Forms.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Graphics.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Graphics.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Materials.Canvas.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Materials.Canvas.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Platform.iOS.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Platform.iOS.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Platform.UI.Android.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Platform.UI.Android.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.StrokeBuilder.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.StrokeBuilder.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.Types3D.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.Types3D.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.VirtualKeyboard.Android.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.VirtualKeyboard.Android.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Android.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Android.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Cocoa.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Cocoa.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Win.pas...
error: embarcadero/sydney/10_4_2/fmx/FMX.WebBrowser.Win.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.App.pas...
error: embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.App.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.Location.pas...
error: embarcadero/sydney/10_4_2/rtl/android/Androidapi.JNI.Location.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/rtl/ios/iOSapi.AVFoundation.pas...
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.AVFoundation.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreImage.pas...
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreImage.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreLocation.pas...
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.CoreLocation.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Foundation.pas...
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Foundation.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Security.pas...
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.Security.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/rtl/ios/iOSapi.UIKit.pas...
error: embarcadero/sydney/10_4_2/rtl/ios/iOSapi.UIKit.pas: No such file or directory
Checking patch embarcadero/sydney/10_4_2/rtl/win/Winapi.Isapi2.pas...
error: embarcadero/sydney/10_4_2/rtl/win/Winapi.Isapi2.pas: No such file or directory

Do I have to modify anything in update.bat?

Thank you very much. I have genuine interest in your component, specially in firemonkey videplayer

**Comment by filiptoskovic** [comment] 2021-05-07 11:01
I think the problem is that the git patch command needs to be run from the Alcinoe root directory instead of the default location, please try.
e.g. I had to run it like this on Rio:
C:\Delphi\3rdParty\alcinoe-master>git apply embarcadero\rio\10_3_3\rio_10_3_3.patch -v

**Comment by juanml1979** [comment] 2021-05-08 20:47
Thank you very much @filiptoskovic!!!!

Solved!

**Comment by Zeus64** [comment] 2021-05-08 21:28
Hmm I will need to study why on some computer it's must be run from the root directoy

**Comment by Zeus64** [comment] 2024-10-29 18:13
Hello, everything has been fixed in the latest committed version.

**Closed by Zeus64** 2024-10-29 18:13 UTC
