### ISSUE TITLE
Problem  with ALVideoPlayer 

### ISSUE THREAD

**Issue by ossamalimon** [MagicFoundation/Alcinoe#211] opened 2021-08-16 10:36 UTC
Hi ;

i do all thing to work with ALVideoPlayer , and it s work fine in my emulator ; But when i install it in my phone i get this :
 
![2476edf1-3b17-4b7b-a2a0-31f423369017](https://user-images.githubusercontent.com/64082995/129550943-004d24d9-759d-4812-b05d-8e0064f0f005.jpg)

the sound works fine but no video image .
Any idea for the solutions ?

and thnx first .

**Comment by RamonSouza96** [comment] 2021-12-20 18:32
@ossamalimon have you added the .jar files to your project library?
If not, it is in "dir : alcinoe-master\lib\jar\com.google.android.exoplayer\" add all .jar in project>android>libraries > right mouse button add

**Comment by yckiong** [comment] 2022-05-07 02:34
I facing same problem, and had added the exoplayer .jar files. Please help.

**Comment by DiamatBR** [comment] 2022-09-30 17:47
Good evening!
I'm having the same problem. Even though I added the ExoPlayer JARs

**Comment by pcplayer** [comment] 2022-10-08 12:48
I can play video file.
My Delphi is 10.4.2 CE version. My Phone is Android 12;

I got the same black screen in the first time I run this test. And after I patch my Delphi, it works fine.

Maybe try patch your delphi by:
1. Alcinoe/tree/master/Embarcadero/Sydney/10_4_2/Update.Bat
2. Then you can get patch files under Alcinoe\embarcadero\sydney\10_4_2,  the update.bat create two folder: rtl and FMX。
3. copy all of these files into your project folder, the re-compile your project.

**Comment by Eaglemaster31** [comment] 2024-03-26 19:12
Have you solve the issue

**Comment by Zeus64** [comment] 2024-03-26 19:26
the problem is that to play video on android you must be able to draw OES texture. the only way right now to draw OES texture on the form is to patch the delphi source code. you can do it localy in alcinoe in an easy way with Alcinoe\Embarcadero\Athens\Update.bat but you need the delphi (alexandria or athens) with the source code included :(

**Comment by Zeus64** [comment] 2024-10-30 10:30
Hello, everything has been fixed in the latest committed version.

**Closed by Zeus64** 2024-10-30 10:30 UTC
